version: "3.9"

services:
  postgres-prod:
    image: postgres:15-alpine
    container_name: postgres-db-prod
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-prod:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    restart: always
    env_file: ./BackEnd/.env
    depends_on:
      postgres-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-prod:
    build: ./FrontEnd
    container_name: frontend-prod
    restart: always

  nginx-prod:
    build:
      context: ./nginx/prod
      dockerfile: Dockerfile
    container_name: nginx-prod
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - frontend-prod
      - backend-prod

volumes:
  postgres-prod-data: