version: "3.9"

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-dev:
    build:
      context:  ./BackEnd
      dockerfile: Dockerfile
    restart: always
    env_file: ./BackEnd/.env
    depends_on:
      postgres-dev:
        condition: service_healthy
    environment:
      DB_HOST: postgres-dev
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: mydb_dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-dev:
    build: ./FrontEnd
    restart: always
    container_name: frontend-dev
  
  nginx-dev:
    build: 
      context: ./nginx/dev
      dockerfile: Dockerfile
    container_name : nginx-dev
    restart : always
    ports :
     - "8080:80"
    depends_on : 
     - frontend-dev
     - backend-dev

volumes:
  postgres-dev-data:


