name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /srv/myprofile/prod
            git pull origin main
            echo 'Listing the files...'
            ls -la

            echo "Injecting environment variables..."
            cat <<EOF > BackEnd/.env
            ACCESS_JWT_SECRET=${{ secrets.ACCESS_JWT_SECRET }}
            REFRESH_JWT_SECRET=${{ secrets.REFRESH_JWT_SECRET }}
            BCRYPT_SALT=${{ secrets.BCRYPT_SALT }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            DATABASE_TYPE=${{ secrets.DATABASE_TYPE }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }}
            EMAIL_APP_ADDRESS=${{ secrets.EMAIL_APP_ADDRESS }}
            ADMIN_ACCOUNT=${{ secrets.ADMIN_ACCOUNT }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            FRONT_URL=${{ secrets.FRONT_URL }}
            FRONT_URL_NO_WWW=${{ secrets.FRONT_URL_NO_WWW }}
            JIRA_TOKEN=${{ secrets.JIRA_TOKEN }}
            JIRA_DOMAIN=${{ secrets.JIRA_DOMAIN }}
            RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}
            VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
            EOF

            echo "Creating FRONTEND .env.production"
            cat <<EOF > FrontEnd/.env.production
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
            EOF

            echo "Creating root .env for docker-compose variable substitution"
            cat <<EOF > .env
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            EOF

            echo "Environment variables injected."
            echo "Rebuilding containers..."

            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d

            echo "Cleaning up unused Docker resources..."
            docker container prune -f
            docker image prune -af